image:
  file: .gitpod.Dockerfile

tasks:
  - name: config Database and npm install
  - init: npm install
  - command: createuser user && createdb mydb

ports:
  - port: 8000
    onOpen: open-browser
