image:
  file: .gitpod.Dockerfile

ports:
  # For App
  - port: 3000
    onOpen: open-browser
    visibility: public

  # For PostGres
  - port: 5432
    onOpen: ignore
    visibility: public

  # For Server
  - port: 3001
    onOpen: ignore
    visibility: public

  #For Flask server
  - port: 5000
    onOpen: ignore
    visibility: public

tasks:
  # - before: cd Server && npm install -g @nestjs/cli && npm install && createuser user && createdb mydb && npm start
  # - command: cd Web && npm install && npm run dev
  - command: cd RecommenderServer && bash Miniconda3-latest-MacOSX-x86_64.sh -b -p /workspace/Carrot-Market-Shorts-1.0/RecommenderServer/miniconda && pip install --upgrade pip && pip install -r requirements.txt

vscode:
  extensions:
    - usernamehw.errorlens
    - dsznajder.es7-react-js-snippets
    - GraphQL.vscode-graphql
    - PKief.material-icon-theme
    - Equinusocio.vsc-material-theme
    - equinusocio.vsc-material-theme-icons
    - esbenp.prettier-vscode
    - humao.rest-client
    - bradlc.vscode-tailwindcss
    - Equinusocio.vsc-community-material-theme
