image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: ignore
    visibility: public

tasks:
  - before: npm install -g @nestjs/cli && npm install
  - init: createuser user && createdb mydb
  - command: npm start
