image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-browser
    visibility: public

  - port: 5432
    onOpen: ignore
    visibility: public

  - port: 3001
    onOpen: ignore
    visibility: public

  - port: 6379
    onOpen: ignore
    visibility: public
tasks:
  - before: cd Server && npm install -g @nestjs/cli && npm install && createuser user && createdb mydb && npm start
  - command: cd Web && npm install && npm run dev
  - command: redis-server
