image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: ignore
    visibility: public

  - port: 5432
    onOpen: ignore
    visibility: public

tasks:
  - before: npm install -g @nestjs/cli && npm install && createuser user && createdb mydb
