image:
  file: .gitpod.Dockerfile

ports:
  # For App
  - port: 3000
    onOpen: open-browser
    visibility: public

  # For PostGres
  - port: 5432
    onOpen: ignore
    visibility: public

  # For Server
  - port: 3001
    onOpen: ignore
    visibility: public

tasks:
  - before: cd Server && npm install -g @nestjs/cli && npm install && createuser user && createdb mydb && npm start
  - command: cd Web && npm install && npm run dev
