


GET http://127.0.0.1:3000/hello

###

POST http://127.0.0.1:3000/signUp 
content-type: application/json

{
   "signUpUser":{
       "userId":"jinseok918111",
       "password":"Lazctlazct93!@",
       "passwordConfirm":"Lazctlazct93!@",
       "email":"jinseok981222@gmail.com",
       "firstName":"jinseok93",
       "lastName":"Seo"
   }
}

###
curl -X POST http://127.0.0.1:3000/login -d '{"email": "jinseok981222@gmail.com", "password": "Lazctlazct93!@"}' -H "Content-Type: application/json"

###
GET http://127.0.0.1:3000/profile 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcklkIjoiamluc2VvazkxODExMSIsImVtYWlsIjoiamluc2Vvazk4MTIyMkBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJqaW5zZW9rOTMiLCJsYXN0TmFtZSI6IlNlbyIsImNvbmZpcm1FbWFpbCI6ZmFsc2UsImlhdCI6MTY0MTk5NzUyNCwiZXhwIjoxNjQyMDAzNTI0fQ.Op2GH0rbcXezVfY5CwbrP0sofdmZTk3l3pfLZRB7-v0
