###

POST http://127.0.0.1:3001/signUp 
content-type: application/json

{
   "signUpUser":{
       "user_name":"jinseok918111",
       "password":"Lazctlazct93!@",
       "password_confirm":"Lazctlazct93!@",
       "email":"jinseok981222@gmail.com",
       "first_name":"jinseok93",
       "last_name":"Seo",
       "expiration_email_time": null
   }
}

###
curl -X POST http://127.0.0.1:3001/login -d '{"email": "jinseok981222@gmail.com", "password": "Lazctlazct93!@"}' -H "Content-Type: application/json"

###
GET http://127.0.0.1:3001/profile 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJqaW5zZW9rOTE4MTExIiwiZW1haWwiOiJqaW5zZW9rOTgxMjIyQGdtYWlsLmNvbSIsImZpcnN0X25hbWUiOiJqaW5zZW9rOTMiLCJsYXN0X25hbWUiOiJTZW8iLCJleHBpcmF0aW9uX2VtYWlsX3RpbWUiOiIyMDIyLTAxLTE5VDA4OjU4OjM0LjYyOVoiLCJjb25maXJtX2VtYWlsIjpmYWxzZSwiaWF0IjoxNjQyNTgyNzE0LCJleHAiOjE2NDI1ODg3MTR9.9yICTmeic61I-Vl95MAslrNsg5Bh15kiMXdYVDje6o4


###
curl "https://api.mockaroo.com/api/6b655b70?count=1000&key=4c733d70" > "Users.json"

###
http://127.0.0.1:3001/confirmEmail/jinseok981222@gmail.com

###
http://127.0.0.1:3001/productData/youtube